#!/bin/bash
# In simple cases, you don't need a config script. 

# With a simple config_panel.toml, you can write in the app settings, in the 
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases 
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

final_path=$(ynh_app_setting_get $app final_path)

# import needed settings
creation_compte=$(ynh_app_setting_get --app="$app" --key=creation_compte)
connexion_compte=$(ynh_app_setting_get --app="$app" --key=connexion_compte)
csv_sep=$(ynh_app_setting_get --app="$app" --key=csv_sep)

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
