#!/bin/bash


source /usr/share/yunohost/helpers

csv_sep=";"
creation_compte=true
connexion_compte=true
ynh_app_setting_set --key=csv_sep --value="$csv_sep"
ynh_app_setting_set --key=creation_compte --value="$creation_compte"
ynh_app_setting_set --key=connexion_compte --value="$connexion_compte"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_hide_warnings mkdir "$install_dir/soap_cache"
ynh_hide_warnings mkdir "$install_dir/composer"

pushd "$install_dir"
	ynh_hide_warnings mv ./www_data/* .
	ynh_mysql_db_shell < db/table.sql
	ynh_mysql_db_shell < db/demo.sql
popd

 #=================================================
 # INSTALL COMPOSER DEPENDENCIES
 #=================================================
 ynh_script_progression "Installing composer dependencies..."

 #REMOVEME? ynh_composer_install
ynh_composer_exec install --no-dev

# worckaround while https://github.com/chartjs/Chart.js/issues/11478 is not fixed
ynh_hide_warnings mkdir "$install_dir/vendor/chartjs"
ynh_hide_warnings curl -o "$install_dir/vendor/chartjs"/chart.js https://cdn.jsdelivr.net/npm/chart.js
ynh_hide_warnings curl -o "$install_dir/vendor/chartjs"/chart.umd.js.map https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.js.map

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="moncycleapp.cron" --destination="/etc/cron.d/$app"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/config.php"

ynh_config_add --template="version.json" --destination="$install_dir/api/version.json"

chmod 655 "$install_dir/api/version.json"
chown $app:www-data "$install_dir/api/version.json"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
