#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# Move config.php to temp folder 
# Can't use the --keep="config.php" option
pushd "$install_dir"
	ynh_exec_warn_less mv ./config.php /tmp/
popd

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace=1

ynh_exec_warn_less mkdir "$install_dir/sessions"
ynh_exec_warn_less mkdir "$install_dir/soap_cache"
ynh_exec_warn_less mkdir "$install_dir/composer"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

pushd "$install_dir"
	ynh_exec_warn_less mv ./www_data/* .
	ynh_exec_warn_less mv /tmp/config.php .
popd

#=================================================
 # SPECIFIC SETUP
 #=================================================
 # INSTALL COMPOSER DEPENDENCIES
 #=================================================
 ynh_script_progression --message="Installing composer dependencies..." --weight=1

 ynh_exec_warn_less ynh_install_composer --phpversion="$phpversion" --composerversion="$YNH_COMPOSER_VERSION" --workdir="$install_dir"

# worckaround while https://github.com/chartjs/Chart.js/issues/11478 is not fixed
ynh_exec_warn_less mkdir "$install_dir/vendor/chartjs"
ynh_exec_warn_less curl -o "$install_dir/vendor/chartjs"/chart.js https://cdn.jsdelivr.net/npm/chart.js

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_add_config --template="../conf/moncycleapp.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
